name: flame_based_games
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.9.2







dependencies:
  flutter:
    sdk: flutter

  
  
  cupertino_icons: ^1.0.8
  flame: ^1.33.0
  go_router: ^16.3.0
  dio: ^5.9.0
  flutter_riverpod: ^3.0.3
  get_it: ^8.2.0
  flutter_tts: ^4.2.3
  uuid: ^4.5.1
  collection: ^1.19.1
  equatable: ^2.0.7
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^5.0.0





flutter:

  
  
  
  uses-material-design: true

  assets:
    - lib/features/bouncing_words_game/docs/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
